services:
  discord-cd:
    build:
      context: ./src
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./projects.json:/app/projects.json:ro
      - ${HOME}/.docker/config.json:/root/.docker/config.json:ro
      - ${HOME}/.password-store:/root/.password-store:ro
      - ${HOME}/.gnupg:/root/.gnupg-host:ro
    restart: unless-stopped
